# Generated by Django 3.0.2 on 2020-01-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='uesr',
            new_name='user',
        ),
    ]
